/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframes;

//import DAO.SementeDAO;
import classes.Semente;

/**
 *
 * @author ramyllo
 */
public class TelaInfo extends javax.swing.JFrame {

    /**
     * Creates new form TelaInfo
     */
    public TelaInfo() {
        initComponents();
        //carregaInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tpInfo = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(tpInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane tpInfo;
    // End of variables declaration//GEN-END:variables

    public void carregaInfo(Semente s) {
      //  sementeDAO s = new sementeDAO();
        
        int id = s.getIdsemente();
        String nome = s.getNome();
        String especie = s.getEspecie();
        int quant = s.getQuant();
        String raridade = s.getRaridade();

        int d_col = s.getDia_col();
        int m_col = s.getMes_col();
        int a_col = s.getAno_col();
        int d_val = s.getDia_val();
        int m_val = s.getMes_val();
        int a_val = s.getAno_val();

        float pcompra = s.getPreco_compra();
        float pvenda = s.getPreco_venda();

        String origem = s.getOrigem();
        String fornecedor = s.getFornecedor();
        String cond_plantil = s.getCondicoes_plantil();
        String obs = s.getObservacoes();
        
        //tpInfo.setText("\n"+id+"\n"+nome+"ndfsnpdnsnsd\n\n naisndaindabdjsada\n asdadad\n\n iasaosmaomsak");
        
        System.out.println("\nId Semente: "+id+"\nNome: "+nome+"\nEspécie: "+especie+"\nQuantidade em Estoque: "+quant+"\nRaridade: "+raridade+"\nData Colheita: "+d_col+"/"+m_col+"/"+a_col+""
                + "\nData Validade: "+d_val+"/"+m_val+"/"+a_val+"\nPreço Compra: "+pcompra+"\nOrigem: "+origem+"\nFornecedor: "+fornecedor+"\nCondições Plantil: "+cond_plantil+"\nObservações: "+obs);
    }

}
