/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Douglas
 */
public class Home extends javax.swing.JFrame {
    
    //Pegar resolução do monitor do usuario
    Toolkit tk = Toolkit.getDefaultToolkit();
    Dimension d = tk.getScreenSize();
    int altura = d.height;
    int largura = d.width;
    
    //Instanciar as JInternalFrames
   TelaAddSemente telaCadSemente = new TelaAddSemente();
   TelaAlterarSemente telaAltSemente = new TelaAlterarSemente();
   TelaApagarSemente telaDelSemente = new TelaApagarSemente();
   
   
   private void fecharJanelas(){
       telaCadSemente.setVisible(false);
       telaAltSemente.setVisible(false);
       telaDelSemente.setVisible(false);
       
   }
  

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setIconImage(Toolkit.getDefaultToolkit().getImage(Home.class.getResource("/icons/background.png")));
	setTitle("Gestor do Armazem de Sementes 1.0");
	setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setBounds(100, 100, largura, altura);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        botaoCadSemente = new javax.swing.JLabel();
        botaoVender = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        botaoAltSemente = new javax.swing.JLabel();
        botaoDelSemente = new javax.swing.JLabel();
        botaoBuscarSemente = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        botaoBalancos = new javax.swing.JLabel();
        botaoGerirVendas = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        botaoCadFornecedor = new javax.swing.JLabel();
        botaoGerirFornecedor = new javax.swing.JLabel();
        painelCentral = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        menuCadSemente = new javax.swing.JMenuItem();
        menuCadFornecedor = new javax.swing.JMenuItem();
        menuNovaVenda = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        menuAltSemente = new javax.swing.JMenuItem();
        menuAltFornecedor = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuDelSemente = new javax.swing.JMenuItem();
        menuDelFornecedor = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        menuListSemente = new javax.swing.JMenuItem();
        menuListFornecedor = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuVerBalancos = new javax.swing.JMenuItem();
        menuGerirVendas = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        menuAjuda = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu9.setText("File");
        jMenuBar2.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar2.add(jMenu10);

        jMenu11.setText("jMenu11");

        jMenu12.setText("jMenu12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botaoCadSemente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Add.png"))); // NOI18N
        botaoCadSemente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadSementeMouseClicked(evt);
            }
        });

        botaoVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Loading.png"))); // NOI18N
        botaoVender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoVenderMouseClicked(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        botaoAltSemente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Modify.png"))); // NOI18N
        botaoAltSemente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoAltSementeMouseClicked(evt);
            }
        });

        botaoDelSemente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Delete.png"))); // NOI18N
        botaoDelSemente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoDelSementeMouseClicked(evt);
            }
        });

        botaoBuscarSemente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Search.png"))); // NOI18N
        botaoBuscarSemente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoBuscarSementeMouseClicked(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        botaoBalancos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Pie Chart.png"))); // NOI18N
        botaoBalancos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoBalancosMouseClicked(evt);
            }
        });

        botaoGerirVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Bar Chart.png"))); // NOI18N
        botaoGerirVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoGerirVendasMouseClicked(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        botaoCadFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Profile.png"))); // NOI18N
        botaoCadFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadFornecedorMouseClicked(evt);
            }
        });

        botaoGerirFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Line Chart.png"))); // NOI18N
        botaoGerirFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoGerirFornecedorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoCadSemente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoVender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoAltSemente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoDelSemente)
                .addGap(8, 8, 8)
                .addComponent(botaoBuscarSemente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoBalancos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoGerirVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoCadFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoGerirFornecedor)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoGerirFornecedor)
                    .addComponent(botaoGerirVendas)
                    .addComponent(botaoBuscarSemente)
                    .addComponent(botaoDelSemente)
                    .addComponent(botaoVender)
                    .addComponent(botaoCadSemente)
                    .addComponent(botaoAltSemente)
                    .addComponent(botaoBalancos)
                    .addComponent(botaoCadFornecedor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelCentral.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout painelCentralLayout = new javax.swing.GroupLayout(painelCentral);
        painelCentral.setLayout(painelCentralLayout);
        painelCentralLayout.setHorizontalGroup(
            painelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        painelCentralLayout.setVerticalGroup(
            painelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );

        jMenu1.setText("Arquivo");

        jMenu5.setText("Novo");

        menuCadSemente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menuCadSemente.setText("Semente");
        menuCadSemente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadSementeActionPerformed(evt);
            }
        });
        jMenu5.add(menuCadSemente);

        menuCadFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        menuCadFornecedor.setText("Fornecedor");
        menuCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadFornecedorActionPerformed(evt);
            }
        });
        jMenu5.add(menuCadFornecedor);

        menuNovaVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        menuNovaVenda.setText("Venda");
        menuNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovaVendaActionPerformed(evt);
            }
        });
        jMenu5.add(menuNovaVenda);

        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenu6.setText("Alterar");

        menuAltSemente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menuAltSemente.setText("Semente");
        menuAltSemente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAltSementeActionPerformed(evt);
            }
        });
        jMenu6.add(menuAltSemente);

        menuAltFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        menuAltFornecedor.setText("Fornecedor");
        menuAltFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAltFornecedorActionPerformed(evt);
            }
        });
        jMenu6.add(menuAltFornecedor);

        jMenu2.add(jMenu6);

        jMenu7.setText("Apagar");

        menuDelSemente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuDelSemente.setText("Semente");
        menuDelSemente.setToolTipText("");
        menuDelSemente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDelSementeActionPerformed(evt);
            }
        });
        jMenu7.add(menuDelSemente);

        menuDelFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        menuDelFornecedor.setText("Fornecedor");
        menuDelFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDelFornecedorActionPerformed(evt);
            }
        });
        jMenu7.add(menuDelFornecedor);

        jMenu2.add(jMenu7);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Exibir");

        jMenu8.setText("Listar");

        menuListSemente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        menuListSemente.setText("Semente");
        menuListSemente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListSementeActionPerformed(evt);
            }
        });
        jMenu8.add(menuListSemente);

        menuListFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        menuListFornecedor.setText("Fornecedor");
        menuListFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListFornecedorActionPerformed(evt);
            }
        });
        jMenu8.add(menuListFornecedor);

        jMenu3.add(jMenu8);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ver");

        menuVerBalancos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        menuVerBalancos.setText("Balanços");
        menuVerBalancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVerBalancosActionPerformed(evt);
            }
        });
        jMenu4.add(menuVerBalancos);

        menuGerirVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        menuGerirVendas.setText("Minhas vendas");
        menuGerirVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerirVendasActionPerformed(evt);
            }
        });
        jMenu4.add(menuGerirVendas);

        jMenuBar1.add(jMenu4);

        jMenu13.setText("Ajuda");

        menuAjuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuAjuda.setText("Sobre");
        menuAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAjudaActionPerformed(evt);
            }
        });
        jMenu13.add(menuAjuda);

        jMenuBar1.add(jMenu13);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(painelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelCentral.setBounds(100,100,largura,altura);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void menuCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadFornecedorActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuCadFornecedorActionPerformed

    private void menuCadSementeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadSementeActionPerformed
        // TODO add your handling code here:
        fecharJanelas();
        painelCentral.add(telaCadSemente);
        telaCadSemente.setVisible(true);
        telaCadSemente.setPosition();
    }//GEN-LAST:event_menuCadSementeActionPerformed

    private void menuListFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListFornecedorActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_menuListFornecedorActionPerformed

    private void botaoCadSementeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadSementeMouseClicked
        fecharJanelas();
        painelCentral.add(telaCadSemente);
        
        telaCadSemente.setVisible(true);
        telaCadSemente.setPosition();
        
        
    }//GEN-LAST:event_botaoCadSementeMouseClicked

    private void botaoAltSementeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAltSementeMouseClicked
        // TODO add your handling code here:
        fecharJanelas();
        painelCentral.add(telaAltSemente);
        telaAltSemente.setVisible(true);
        telaAltSemente.setPosition();
    }//GEN-LAST:event_botaoAltSementeMouseClicked

    private void botaoDelSementeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoDelSementeMouseClicked
        // TODO add your handling code here:
        fecharJanelas();
        painelCentral.add(telaDelSemente);
        telaDelSemente.setVisible(true);
        telaDelSemente.setPosition();
    }//GEN-LAST:event_botaoDelSementeMouseClicked

    private void botaoBuscarSementeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoBuscarSementeMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_botaoBuscarSementeMouseClicked

    private void botaoBalancosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoBalancosMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_botaoBalancosMouseClicked

    private void botaoGerirVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoGerirVendasMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_botaoGerirVendasMouseClicked

    private void botaoCadFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadFornecedorMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_botaoCadFornecedorMouseClicked

    private void botaoGerirFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoGerirFornecedorMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_botaoGerirFornecedorMouseClicked

    private void botaoVenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVenderMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_botaoVenderMouseClicked

    private void menuNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovaVendaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuNovaVendaActionPerformed

    private void menuAltSementeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAltSementeActionPerformed
        // TODO add your handling code here:
        fecharJanelas();
        painelCentral.add(telaAltSemente);
        telaAltSemente.setVisible(true);
        telaAltSemente.setPosition();
    }//GEN-LAST:event_menuAltSementeActionPerformed

    private void menuAltFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAltFornecedorActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_menuAltFornecedorActionPerformed

    private void menuDelFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDelFornecedorActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuDelFornecedorActionPerformed

    private void menuDelSementeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDelSementeActionPerformed
        // TODO add your handling code here:
        fecharJanelas();
        painelCentral.add(telaDelSemente);
        telaDelSemente.setVisible(true);
        telaDelSemente.setPosition();
    }//GEN-LAST:event_menuDelSementeActionPerformed

    private void menuListSementeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListSementeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuListSementeActionPerformed

    private void menuVerBalancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVerBalancosActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_menuVerBalancosActionPerformed

    private void menuAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAjudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAjudaActionPerformed

    private void menuGerirVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerirVendasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuGerirVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botaoAltSemente;
    private javax.swing.JLabel botaoBalancos;
    private javax.swing.JLabel botaoBuscarSemente;
    private javax.swing.JLabel botaoCadFornecedor;
    private javax.swing.JLabel botaoCadSemente;
    private javax.swing.JLabel botaoDelSemente;
    private javax.swing.JLabel botaoGerirFornecedor;
    private javax.swing.JLabel botaoGerirVendas;
    private javax.swing.JLabel botaoVender;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JMenuItem menuAjuda;
    private javax.swing.JMenuItem menuAltFornecedor;
    private javax.swing.JMenuItem menuAltSemente;
    private javax.swing.JMenuItem menuCadFornecedor;
    private javax.swing.JMenuItem menuCadSemente;
    private javax.swing.JMenuItem menuDelFornecedor;
    private javax.swing.JMenuItem menuDelSemente;
    private javax.swing.JMenuItem menuGerirVendas;
    private javax.swing.JMenuItem menuListFornecedor;
    private javax.swing.JMenuItem menuListSemente;
    private javax.swing.JMenuItem menuNovaVenda;
    private javax.swing.JMenuItem menuVerBalancos;
    private javax.swing.JPanel painelCentral;
    // End of variables declaration//GEN-END:variables
}
